// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9NqyCnkenFk0nKydIr3-p3esD8jE9BwQ',
    appId: '1:1054017338857:android:3931a59e833b8ecaa4df78',
    messagingSenderId: '1054017338857',
    projectId: 'quizapp-9df22',
    storageBucket: 'quizapp-9df22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJqj18KMsXf2S_7xuii24A9zjk8hM6UxE',
    appId: '1:1054017338857:ios:b5d3705be2077442a4df78',
    messagingSenderId: '1054017338857',
    projectId: 'quizapp-9df22',
    storageBucket: 'quizapp-9df22.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAusq9-ViG_F-9uOHKVslLVlB-12n3XiE4',
    appId: '1:1054017338857:web:97cb100e0d20fdd9a4df78',
    messagingSenderId: '1054017338857',
    projectId: 'quizapp-9df22',
    authDomain: 'quizapp-9df22.firebaseapp.com',
    storageBucket: 'quizapp-9df22.firebasestorage.app',
  );
}
